"""initial schema

Revision ID: 133b5978bcff
Revises: 
Create Date: 2026-09-12 09:20:34.897162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '133b5978bcff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flights',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('flight_number', sa.String(length=10), nullable=False),
    sa.Column('airline', sa.String(length=100), nullable=False),
    sa.Column('airline_code', sa.String(length=3), nullable=False),
    sa.Column('origin', sa.String(length=3), nullable=False),
    sa.Column('destination', sa.String(length=3), nullable=False),
    sa.Column('origin_city', sa.String(length=100), nullable=False),
    sa.Column('destination_city', sa.String(length=100), nullable=False),
    sa.Column('origin_country', sa.String(length=100), nullable=False),
    sa.Column('destination_country', sa.String(length=100), nullable=False),
    sa.Column('departure_time', sa.DateTime(), nullable=False),
    sa.Column('arrival_time', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('stops', sa.Integer(), nullable=False),
    sa.Column('stop_airports', sa.Text(), nullable=True),
    sa.Column('cabin_class', sa.Enum('ECONOMY', 'PREMIUM_ECONOMY', 'BUSINESS', 'FIRST', name='cabinclass'), nullable=False),
    sa.Column('base_price', sa.Float(), nullable=False),
    sa.Column('tax_percent', sa.Float(), nullable=False),
    sa.Column('carry_on_kg', sa.Integer(), nullable=False),
    sa.Column('checked_baggage_kg', sa.Integer(), nullable=False),
    sa.Column('total_seats', sa.Integer(), nullable=False),
    sa.Column('available_seats', sa.Integer(), nullable=False),
    sa.Column('aircraft_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'DELAYED', 'CANCELLED', 'COMPLETED', name='flightstatus'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('available_seats >= 0', name='ck_flight_seats_nonneg'),
    sa.CheckConstraint('base_price > 0', name='ck_flight_price_positive'),
    sa.CheckConstraint('stops >= 0', name='ck_flight_stops_nonneg'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flights_departure_time'), 'flights', ['departure_time'], unique=False)
    op.create_index(op.f('ix_flights_destination'), 'flights', ['destination'], unique=False)
    op.create_index(op.f('ix_flights_flight_number'), 'flights', ['flight_number'], unique=False)
    op.create_index(op.f('ix_flights_origin'), 'flights', ['origin'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('membership', sa.Enum('STANDARD', 'SILVER', 'GOLD', 'PLATINUM', name='membershiptier'), nullable=False),
    sa.Column('loyalty_points', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('bookings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pnr', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('flight_id', sa.String(length=36), nullable=False),
    sa.Column('cabin_class', sa.String(length=30), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', name='bookingstatus'), nullable=False),
    sa.Column('passenger_count', sa.Integer(), nullable=False),
    sa.Column('base_amount', sa.Float(), nullable=False),
    sa.Column('tax_amount', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_flight_id'), 'bookings', ['flight_id'], unique=False)
    op.create_index(op.f('ix_bookings_pnr'), 'bookings', ['pnr'], unique=True)
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    op.create_table('passengers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('booking_id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.String(length=10), nullable=False),
    sa.Column('passport_number', sa.String(length=50), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('passenger_type', sa.Enum('ADULT', 'CHILD', 'INFANT', name='passengertype'), nullable=False),
    sa.Column('seat_number', sa.String(length=5), nullable=True),
    sa.Column('meal_preference', sa.String(length=50), nullable=True),
    sa.Column('special_assistance', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passengers_booking_id'), 'passengers', ['booking_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('booking_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('method', sa.Enum('CREDIT_CARD', 'DEBIT_CARD', 'STRIPE', 'SIMULATED', name='paymentmethod'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCEEDED', 'FAILED', name='paymentstatus'), nullable=False),
    sa.Column('stripe_checkout_session_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_charge_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_event_id', sa.String(length=255), nullable=True),
    sa.Column('card_last_four', sa.String(length=4), nullable=True),
    sa.Column('gateway_response', sa.Text(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_booking_id'), 'payments', ['booking_id'], unique=True)
    op.create_index(op.f('ix_payments_stripe_charge_id'), 'payments', ['stripe_charge_id'], unique=False)
    op.create_index(op.f('ix_payments_stripe_checkout_session_id'), 'payments', ['stripe_checkout_session_id'], unique=False)
    op.create_index(op.f('ix_payments_stripe_event_id'), 'payments', ['stripe_event_id'], unique=False)
    op.create_index(op.f('ix_payments_stripe_payment_intent_id'), 'payments', ['stripe_payment_intent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_stripe_payment_intent_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_stripe_event_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_stripe_checkout_session_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_stripe_charge_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_booking_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_passengers_booking_id'), table_name='passengers')
    op.drop_table('passengers')
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_pnr'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_flight_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_flights_origin'), table_name='flights')
    op.drop_index(op.f('ix_flights_flight_number'), table_name='flights')
    op.drop_index(op.f('ix_flights_destination'), table_name='flights')
    op.drop_index(op.f('ix_flights_departure_time'), table_name='flights')
    op.drop_table('flights')
    # PostgreSQL native ENUM types are created implicitly with their tables on
    # upgrade (above), but Alembic's ``op.drop_table`` does not remove them.
    # Drop them explicitly so a downgrade leaves PostgreSQL fully clean.
    # No-ops on SQLite, where enum columns are emulated with VARCHAR + CHECK.
    enum_cabin = sa.Enum('ECONOMY', 'PREMIUM_ECONOMY', 'BUSINESS', 'FIRST', name='cabinclass')
    enum_flight_status = sa.Enum('SCHEDULED', 'DELAYED', 'CANCELLED', 'COMPLETED', name='flightstatus')
    enum_membership = sa.Enum('STANDARD', 'SILVER', 'GOLD', 'PLATINUM', name='membershiptier')
    enum_booking_status = sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', name='bookingstatus')
    enum_passenger_type = sa.Enum('ADULT', 'CHILD', 'INFANT', name='passengertype')
    enum_payment_method = sa.Enum('CREDIT_CARD', 'DEBIT_CARD', 'STRIPE', 'SIMULATED', name='paymentmethod')
    enum_payment_status = sa.Enum('PENDING', 'SUCCEEDED', 'FAILED', name='paymentstatus')
    for enum_type in (enum_cabin, enum_flight_status, enum_membership, enum_booking_status,
                      enum_passenger_type, enum_payment_method, enum_payment_status):
        enum_type.drop(op.get_bind())
    # ### end Alembic commands ###